name: dart_docx
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/insinfo/dart_docx

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  #intl: ^0.15.8
  xml: '>=5.0.0 <7.0.0' 
  archive: '>=3.0.0 <4.0.0'

dev_dependencies:    
  pedantic: any
  test: any